[package]
edition.workspace = true
license.workspace = true
name = "sofia-models-manager"
version.workspace = true

[lib]
doctest = false
name = "sofia_models_manager"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
sofia-collaboration-mode-templates = { workspace = true }
sofia-http-client = { workspace = true }
sofia-login = { workspace = true }
sofia-otel = { workspace = true }
sofia-protocol = { workspace = true }
sofia-utils-output-truncation = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "sync", "time"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
