[package]
edition.workspace = true
license.workspace = true
name = "sofia-analytics"
version.workspace = true

[lib]
doctest = false
name = "sofia_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
sofia-app-server-protocol = { workspace = true }
sofia-git-utils = { workspace = true }
sofia-login = { workspace = true }
sofia-model-provider = { workspace = true }
sofia-plugin = { workspace = true }
sofia-protocol = { workspace = true }
sofia-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
sofia-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
