[package]
edition.workspace = true
license.workspace = true
name = "sofia-plugin"
version.workspace = true

[lib]
doctest = false
name = "sofia_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
sofia-config = { workspace = true }
sofia-protocol = { workspace = true }
sofia-utils-absolute-path = { workspace = true }
sofia-utils-path-uri = { workspace = true }
sofia-utils-plugins = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
